Save credential into temporary folder

diff --git a/jenkins/PerfCI_Chaos/03_PerfCI_Choas_Windows_VMs_Deployment/Jenkinsfile b/jenkins/PerfCI_Chaos/03_PerfCI_Choas_Windows_VMs_Deployment/Jenkinsfile
--- a/jenkins/PerfCI_Chaos/03_PerfCI_Choas_Windows_VMs_Deployment/Jenkinsfile
+++ b/jenkins/PerfCI_Chaos/03_PerfCI_Choas_Windows_VMs_Deployment/Jenkinsfile
@@ -21,9 +21,9 @@ pipeline {
         GOOGLE_DRIVE_PATH = credentials('perfci_google_drive_path')
         GOOGLE_DRIVE_CREDENTIALS_FILE = credentials('perfci_google_drive_credentials_file')
         GOOGLE_DRIVE_TOKEN_FILE = credentials('perfci_google_drive_token_file')
-        CREDENTIALS_FILE = credentials('perfci_credentials_file')
-        TOKEN_FILE = credentials('perfci_token_file')
-        DESTINATION_PATH = credentials('perfci_destination_path')
+        GOOGLE_CREDENTIALS_FILE = credentials('perfci_google_credentials_file')
+        GOOGLE_TOKEN_FILE = credentials('perfci_google_token_file')
+        GOOGLE_DESTINATION_PATH = credentials('perfci_google_destination_path')
         GOOGLE_DRIVE_SHARED_DRIVE_ID = credentials('perfci_google_drive_shared_drive_id')
         RUN_ARTIFACTS_URL = credentials('perfci_run_artifacts_url')
         REDIS = credentials('perfci_redis')
@@ -112,30 +112,29 @@ END
             }
         }
 
-        stage('Prepare Google credential files') {
+        stage('Prepare Google Credential Files') {
             steps {
-                    script {
-                        // Assign the file path to the environment variable
-                        env.GOOGLE_DRIVE_CREDENTIALS = "${env.WORKSPACE}/${CREDENTIALS_FILE}"
-                        env.GOOGLE_DRIVE_TOKEN = "${env.WORKSPACE}/${TOKEN_FILE}"
+                script {
 
-                        sh """
-                        echo "Checking if ${env.GOOGLE_DRIVE_CREDENTIALS} exists..."
-                        if [[ -f "${env.GOOGLE_DRIVE_CREDENTIALS}" ]]; then
-                            echo "File exists. Deleting it..."
-                            rm -f "${env.GOOGLE_DRIVE_CREDENTIALS}"
-                        fi
-                        echo "Checking if ${env.GOOGLE_DRIVE_TOKEN} exists..."
-                        if [[ -f "${env.GOOGLE_DRIVE_TOKEN}" ]]; then
-                            echo "File exists. Deleting it..."
-                            rm -f "${env.GOOGLE_DRIVE_TOKEN}"
-                        fi
-
-                        echo "Copying secret file to the temporary local file..."
-                        cp "$GOOGLE_DRIVE_CREDENTIALS_FILE" "${env.GOOGLE_DRIVE_CREDENTIALS}"
-                        cp "$GOOGLE_DRIVE_TOKEN_FILE" "${env.GOOGLE_DRIVE_TOKEN}"
-                        """
+                    // Create a unique temp directory
+                    env.TEMP_DIR = sh(script: "mktemp -d -p '${env.WORKSPACE}'", returnStdout: true).trim()
+                    if (!env.TEMP_DIR) {
+                        error "Failed to create temporary directory!"
                     }
+                    echo "Temporary directory created: ${env.TEMP_DIR}"
+
+                    // Set up file paths
+                    env.GOOGLE_DRIVE_CREDENTIALS = "${env.TEMP_DIR}/${GOOGLE_CREDENTIALS_FILE}"
+                    env.GOOGLE_DRIVE_TOKEN = "${env.TEMP_DIR}/${GOOGLE_TOKEN_FILE}"
+
+                    // Prepare credential files
+                    sh """
+                        set -e
+                        cp '${GOOGLE_DRIVE_CREDENTIALS_FILE}' '${env.GOOGLE_DRIVE_CREDENTIALS}' || error "Failed to copy ${GOOGLE_DRIVE_CREDENTIALS_FILE}"
+                        cp '${GOOGLE_DRIVE_TOKEN_FILE}' '${env.GOOGLE_DRIVE_TOKEN}' || error "Failed to copy ${GOOGLE_DRIVE_TOKEN_FILE}"
+                        chmod 600 '${env.GOOGLE_DRIVE_CREDENTIALS}' '${env.GOOGLE_DRIVE_TOKEN}' || error "Failed to set permissions on credential files"
+                    """
+                }
             }
         }
 
@@ -227,8 +226,8 @@ END
                                         -e IBM_BUCKET='${IBM_BUCKET}' \
                                         -e IBM_KEY='${IBM_KEY}' \
                                         -e GOOGLE_DRIVE_PATH='${GOOGLE_DRIVE_PATH}' \
-                                        -e GOOGLE_DRIVE_CREDENTIALS_FILE='${DESTINATION_PATH}/${CREDENTIALS_FILE}' \
-                                        -e GOOGLE_DRIVE_TOKEN_FILE='${DESTINATION_PATH}/${TOKEN_FILE}' \
+                                        -e GOOGLE_DRIVE_CREDENTIALS_FILE='${GOOGLE_DESTINATION_PATH}/${GOOGLE_CREDENTIALS_FILE}' \
+                                        -e GOOGLE_DRIVE_TOKEN_FILE='${GOOGLE_DESTINATION_PATH}/${GOOGLE_TOKEN_FILE}' \
                                         -e GOOGLE_DRIVE_SHARED_DRIVE_ID='${GOOGLE_DRIVE_SHARED_DRIVE_ID}' \
                                         -e RUN_ARTIFACTS_URL='${RUN_ARTIFACTS_URL}' \
                                         -e BUILD_VERSION='${build_version}' \
@@ -248,7 +247,7 @@ END
                                         -e TIMEOUT='${TIMEOUT}' \
                                         -e log_level='INFO' \
                                         -v '${KUBECONFIG_PATH}:${KUBECONFIG_PATH}' \
-                                        -v '${WORKSPACE}:${DESTINATION_PATH}' \
+                                        -v '${TEMP_DIR}:${GOOGLE_DESTINATION_PATH}' \
                                         --privileged '${QUAY_BENCHMARK_RUNNER_REPOSITORY}'
                                     """
                                     success = true
@@ -277,6 +276,14 @@ END
         always {
             script {
                 sh 'sudo podman ps -a --filter "name=benchmark-runner" -q | xargs -r podman rm -f'
+                sh '''
+                # Clean up the virtual environment
+                rm -rf venv
+                if [ -d "${TEMP_DIR}" ]; then
+                    rm -rf "${TEMP_DIR}"
+                    echo "Temporary directory '${TEMP_DIR}' deleted."
+                fi
+                '''
             }
         }
         failure {
