Save Google Drive credentials to a temporary folder

diff --git a/jenkins/PerfCI_Chaos/05_PerfCI_Chaos_Verify_Windows_VMs_Deployment/Jenkinsfile b/jenkins/PerfCI_Chaos/05_PerfCI_Chaos_Verify_Windows_VMs_Deployment/Jenkinsfile
--- a/jenkins/PerfCI_Chaos/05_PerfCI_Chaos_Verify_Windows_VMs_Deployment/Jenkinsfile
+++ b/jenkins/PerfCI_Chaos/05_PerfCI_Chaos_Verify_Windows_VMs_Deployment/Jenkinsfile
@@ -22,9 +22,9 @@ pipeline {
         GOOGLE_DRIVE_CREDENTIALS_FILE = credentials('perfci_google_drive_credentials_file')
         GOOGLE_DRIVE_TOKEN_FILE = credentials('perfci_google_drive_token_file')
         GOOGLE_DRIVE_SHARED_DRIVE_ID = credentials('perfci_google_drive_shared_drive_id')
-        CREDENTIALS_FILE = credentials('perfci_credentials_file')
-        TOKEN_FILE = credentials('perfci_token_file')
-        DESTINATION_PATH = credentials('perfci_destination_path')
+        GOOGLE_CREDENTIALS_FILE = 'credentials.json'
+        GOOGLE_TOKEN_FILE = 'token.json'
+        GOOGLE_DESTINATION_PATH = '/tmp'
         RUN_ARTIFACTS_URL = credentials('perfci_run_artifacts_url')
         REDIS = credentials('perfci_redis')
         WORKER_DISK_IDS = credentials('perfci_worker_disk_ids')
@@ -55,12 +55,13 @@ pipeline {
         THREADS_LIMIT= 20
         PROVISION_TIMEOUT = 3600
         TIMEOUT = 8000
+        WORKSPACE_PATH = "${env.WORKSPACE}/workspace/${env.JOB_NAME}/"
     }
     stages {
         stage('Cleanup') {
             steps {
                 script {
-                    // Clean the Jenkins workspace
+                        // Clean the Jenkins workspace
                         echo "Cleaning Jenkins workspace"
                         deleteDir()
                         sh '''
@@ -110,30 +111,27 @@ END
             }
         }
 
-        stage('Prepare Google credential files') {
+        stage('Prepare Google Credential Files') {
             steps {
-                    script {
-                        // Assign the file path to the environment variable
-                        env.GOOGLE_DRIVE_CREDENTIALS = "${env.WORKSPACE}/${CREDENTIALS_FILE}"
-                        env.GOOGLE_DRIVE_TOKEN = "${env.WORKSPACE}/${TOKEN_FILE}"
-
-                        sh """
-                        echo "Checking if ${env.GOOGLE_DRIVE_CREDENTIALS} exists..."
-                        if [[ -f "${env.GOOGLE_DRIVE_CREDENTIALS}" ]]; then
-                            echo "File exists. Deleting it..."
-                            rm -f "${env.GOOGLE_DRIVE_CREDENTIALS}"
-                        fi
-                        echo "Checking if ${env.GOOGLE_DRIVE_TOKEN} exists..."
-                        if [[ -f "${env.GOOGLE_DRIVE_TOKEN}" ]]; then
-                            echo "File exists. Deleting it..."
-                            rm -f "${env.GOOGLE_DRIVE_TOKEN}"
-                        fi
-
-                        echo "Copying secret file to the temporary local file..."
-                        cp "$GOOGLE_DRIVE_CREDENTIALS_FILE" "${env.GOOGLE_DRIVE_CREDENTIALS}"
-                        cp "$GOOGLE_DRIVE_TOKEN_FILE" "${env.GOOGLE_DRIVE_TOKEN}"
-                        """
+                script {
+                    // Create a unique temp directory
+                    env.TEMP_DIR = sh(script: "umask 77; mktemp -d -p '${env.WORKSPACE_PATH}'", returnStdout: true).trim()
+                    if (!env.TEMP_DIR) {
+                        error "Failed to create temporary directory!"
                     }
+
+                    // Set file paths
+                    env.GOOGLE_DRIVE_CREDENTIALS = "${env.TEMP_DIR}/${GOOGLE_CREDENTIALS_FILE}"
+                    env.GOOGLE_DRIVE_TOKEN = "${env.TEMP_DIR}/${GOOGLE_TOKEN_FILE}"
+
+                    // Prepare credential files
+                    sh """
+                        set -e
+                        umask 77
+                        cp '${GOOGLE_DRIVE_CREDENTIALS_FILE}' '${env.GOOGLE_DRIVE_CREDENTIALS}' || error "Failed to copy ${GOOGLE_DRIVE_CREDENTIALS_FILE}"
+                        cp '${GOOGLE_DRIVE_TOKEN_FILE}' '${env.GOOGLE_DRIVE_TOKEN}' || error "Failed to copy ${GOOGLE_DRIVE_TOKEN_FILE}"
+                    """
+                }
             }
         }
 
@@ -202,8 +200,8 @@ END
                                         -e IBM_BUCKET='${IBM_BUCKET}' \
                                         -e IBM_KEY='${IBM_KEY}' \
                                         -e GOOGLE_DRIVE_PATH='${GOOGLE_DRIVE_PATH}' \
-                                        -e GOOGLE_DRIVE_CREDENTIALS_FILE='${DESTINATION_PATH}/${CREDENTIALS_FILE}' \
-                                        -e GOOGLE_DRIVE_TOKEN_FILE='${DESTINATION_PATH}/${TOKEN_FILE}' \
+                                        -e GOOGLE_DRIVE_CREDENTIALS_FILE='${GOOGLE_DESTINATION_PATH}/${GOOGLE_CREDENTIALS_FILE}' \
+                                        -e GOOGLE_DRIVE_TOKEN_FILE='${GOOGLE_DESTINATION_PATH}/${GOOGLE_TOKEN_FILE}' \
                                         -e GOOGLE_DRIVE_SHARED_DRIVE_ID='${GOOGLE_DRIVE_SHARED_DRIVE_ID}' \
                                         -e RUN_ARTIFACTS_URL='${RUN_ARTIFACTS_URL}' \
                                         -e BUILD_VERSION='${build_version}' \
@@ -223,7 +221,7 @@ END
                                         -e TIMEOUT='${TIMEOUT}' \
                                         -e log_level='INFO' \
                                         -v '${KUBECONFIG_PATH}:${KUBECONFIG_PATH}' \
-                                        -v '${WORKSPACE}:${DESTINATION_PATH}' \
+                                        -v '${TEMP_DIR}:${GOOGLE_DESTINATION_PATH}' \
                                         --privileged '${QUAY_BENCHMARK_RUNNER_REPOSITORY}'
                                     """
                                     success = true
@@ -251,7 +249,16 @@ END
     post {
         always {
             script {
-                sh 'sudo podman ps -a --filter "name=benchmark-runner" -q | xargs -r podman rm -f'
+                sh '''
+                    sudo podman ps -a --filter "name=benchmark-runner" -q | xargs -r podman rm -f
+                    # Clean up the virtual environment
+                    rm -rf venv
+                    # Clean temp dir
+                    if [ -d "${TEMP_DIR}" ]; then
+                        sudo rm -rf "${TEMP_DIR}"
+                        echo "Temporary directory '${TEMP_DIR}' deleted."
+                    fi
+                '''
             }
         }
         failure {
